<a href="https://colab.research.google.com/github/vikrantyadav11234/NLP_Practice/blob/main/RNN_Architecture_Foundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, SimpleRNN
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
model =Sequential()
model.add(SimpleRNN(3, input_shape= (4,5))) # sequence= batch size, timesteps, input-feature
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.get_weights()[0].shape)

(5, 3)


In [ ]:
print(model.get_weights()[0]) # 5 inputs are connected to 3 neurons (5X3)
# Random initialization
# In simple RNN neurons output is also connecte to self and other neurons also. (3X3)
print(model.get_weights()[1])

[[ 0.733643    0.11410391 -0.5422902 ]
 [ 0.23498863 -0.24159986  0.68319994]
 [ 0.40681022 -0.40840873  0.15688628]
 [-0.5247058  -0.5396054   0.27628332]
 [-0.19587749 -0.7160811   0.7511582 ]]
[[-0.2018702  -0.9121139   0.35678673]
 [ 0.90700275 -0.31156552 -0.28332487]
 [-0.36958703 -0.2664117  -0.89018553]]


In [ ]:
print(model.get_weights()[2])

[0. 0. 0.]


In [ ]:
print(model.get_weights()[3])

[[ 0.01795232]
 [ 0.13054323]
 [-0.9776777 ]]


In [ ]:
print(model.get_weights()[4])

[0.]


# Integer encoding method in RNN

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
docs =['rnn lstm', 'lstm lstm', 'gru rnn', 'nlp tableau powerbi',
       'sas python r stats ml dl computervision ai',
       'python jupytor notebook',
       'r sas sas python', 'modiji lost the election',
       'rahul baba won the election', 'nda vs india']
docs

['rnn lstm',
 'lstm lstm',
 'gru rnn',
 'nlp tableau powerbi',
 'sas python r stats ml dl computervision ai',
 'python jupytor notebook',
 'r sas sas python',
 'modiji lost the election',
 'rahul baba won the election',
 'nda vs india']

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5, 2],
 [2, 2],
 [9, 5],
 [10, 11, 12],
 [3, 4, 6, 13, 14, 15, 16, 17],
 [4, 18, 19],
 [6, 3, 3, 4],
 [20, 21, 7, 8],
 [22, 23, 24, 7, 8],
 [25, 26, 27]]

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<vikrant>')
# out of vocab - oov


In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index

{'<vikrant>': 1,
 'lstm': 2,
 'sas': 3,
 'python': 4,
 'rnn': 5,
 'r': 6,
 'the': 7,
 'election': 8,
 'gru': 9,
 'nlp': 10,
 'tableau': 11,
 'powerbi': 12,
 'stats': 13,
 'ml': 14,
 'dl': 15,
 'computervision': 16,
 'ai': 17,
 'jupytor': 18,
 'notebook': 19,
 'modiji': 20,
 'lost': 21,
 'rahul': 22,
 'baba': 23,
 'won': 24,
 'nda': 25,
 'vs': 26,
 'india': 27}

In [ ]:
tokenizer.word_counts

OrderedDict([('rnn', 2),
             ('lstm', 3),
             ('gru', 1),
             ('nlp', 1),
             ('tableau', 1),
             ('powerbi', 1),
             ('sas', 3),
             ('python', 3),
             ('r', 2),
             ('stats', 1),
             ('ml', 1),
             ('dl', 1),
             ('computervision', 1),
             ('ai', 1),
             ('jupytor', 1),
             ('notebook', 1),
             ('modiji', 1),
             ('lost', 1),
             ('the', 2),
             ('election', 2),
             ('rahul', 1),
             ('baba', 1),
             ('won', 1),
             ('nda', 1),
             ('vs', 1),
             ('india', 1)])

In [ ]:
tokenizer.document_count

10

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5, 2],
 [2, 2],
 [9, 5],
 [10, 11, 12],
 [3, 4, 6, 13, 14, 15, 16, 17],
 [4, 18, 19],
 [6, 3, 3, 4],
 [20, 21, 7, 8],
 [22, 23, 24, 7, 8],
 [25, 26, 27]]

In [ ]:
# we will make timesteps =8 because max len of the sentence is 8.
# vectors which are having less no, zero padding is used to fill the remaining places.
# padding has two methods 1. pre padding  2. post padding

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences1 = pad_sequences(sequences, maxlen=8, padding='post')

sequences1


array([[ 5,  2,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  0,  0,  0,  0,  0,  0],
       [ 9,  5,  0,  0,  0,  0,  0,  0],
       [10, 11, 12,  0,  0,  0,  0,  0],
       [ 3,  4,  6, 13, 14, 15, 16, 17],
       [ 4, 18, 19,  0,  0,  0,  0,  0],
       [ 6,  3,  3,  4,  0,  0,  0,  0],
       [20, 21,  7,  8,  0,  0,  0,  0],
       [22, 23, 24,  7,  8,  0,  0,  0],
       [25, 26, 27,  0,  0,  0,  0,  0]], dtype=int32)

# Integer encoding Method in RNN or going forword we prefer to use embedding method only.

#### IMDB movie review sentiment classification dataset

In [ ]:
from keras.datasets import imdb
from keras.layers import Embedding , Flatten

In [ ]:
(x_train, y_train), (x_test, y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(25000,)
(25000,)
(25000,)
(25000,)


In [ ]:
x_train[0]  # already tokenized data

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
print(len(x_train[0]))

218


In [ ]:
print(len(x_train[1]))

189


In [ ]:
x_train = pad_sequences(x_train, padding='post') # hyperparameter tuning
x_test = pad_sequences(x_test, padding= 'post')

In [ ]:
len(x_train[0])

2494

In [ ]:
x_train = pad_sequences(x_train, padding='post', maxlen=50) # hyperparameter tuning
x_test = pad_sequences(x_test, padding= 'post', maxlen=50)
# to reduce the complexity hyperparameter tuning
# If we use pre padding, first 50 zeros will come only so always try to use post padding

In [ ]:
len(x_train[0])

50

In [ ]:
# Build the model
model = Sequential()
model.add(SimpleRNN(32, input_shape=(50,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Build the model
model = Sequential()
model.add(SimpleRNN(32, input_shape=(50,1)))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/5
782/782 [==============================] - 12s 14ms/step - loss: 0.6933 - accuracy: 0.5070 - val_loss: 0.6934 - val_accuracy: 0.5000
Epoch 2/5
782/782 [==============================] - 10s 13ms/step - loss: 0.6932 - accuracy: 0.5026 - val_loss: 0.6935 - val_accuracy: 0.5000
Epoch 3/5
782/782 [==============================] - 10s 12ms/step - loss: 0.6933 - accuracy: 0.4970 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 4/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6932 - accuracy: 0.5011 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 5/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6932 - accuracy: 0.4985 - val_loss: 0.6932 - val_accuracy: 0.5000


## RNN with embedding method
* Please note we have to use most of the time embedding method only as it give batter result.

In [ ]:
x_train = pad_sequences(x_train, padding='post', maxlen=50) # hyperparameter tuning
x_test = pad_sequences(x_test, padding= 'post', maxlen=50)

In [ ]:
x_train.shape

(25000, 50)

In [ ]:
x_train = np.clip(x_train, 0, 24999)

In [ ]:
model = Sequential()
model.add(Embedding(32, output_dim=2, input_length=5))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              64        
                                                                 
Total params: 64 (256.00 Byte)
Trainable params: 64 (256.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


#
* By using embedding we can reduce the complexity.

In [ ]:
model = Sequential()
model.add(Embedding(25000,5))
model.add(SimpleRNN(32, return_sequences=False))
# input_sequences =False means i don want to see previous results i want to see the last result only.
# True for POS, Name entity recognititon
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 5)           125000    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1216      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 126249 (493.16 KB)
Trainable params: 126249 (493.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
y_train.shape

(25000,)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))


Epoch 1/5
782/782 [==============================] - 45s 54ms/step - loss: 0.6933 - accuracy: 0.5036 - val_loss: 0.6933 - val_accuracy: 0.5000
Epoch 2/5
782/782 [==============================] - 40s 52ms/step - loss: 0.6932 - accuracy: 0.5053 - val_loss: 0.6934 - val_accuracy: 0.5000
Epoch 3/5
782/782 [==============================] - 39s 51ms/step - loss: 0.6932 - accuracy: 0.5014 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 4/5
782/782 [==============================] - 39s 50ms/step - loss: 0.6932 - accuracy: 0.5019 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 5/5
782/782 [==============================] - 39s 51ms/step - loss: 0.6932 - accuracy: 0.5000 - val_loss: 0.6932 - val_accuracy: 0.5000
